#ifndef MATHIS_TEMP_CONFIG_H
#define MATHIS_TEMP_CONFIG_H

/* 温度上下限单位为摄氏度，确认/恢复计数单位为采样次数。
 * 电量 mV 为现有采样换算口径；分压比及单节/整组含义待硬件确认。 */

#define PROBE_TEMP_C_LOW_LIMIT   (0)
#define PROBE_TEMP_C_HIGH_LIMIT  (500)
#define PROBE_TEMP_C_HIGH_RELEASE (PROBE_TEMP_C_HIGH_LIMIT)
#define PROBE_TEMP_HI_CONFIRM_COUNT (3u)
#define PROBE_TEMP_HI_RELEASE_CONFIRM_COUNT (2u)
#define PROBE_TEMP_LO_CONFIRM_COUNT (3u)
#define PROBE_TEMP_LO_RELEASE_CONFIRM_COUNT (2u)
#define PROBE_DISCONNECT_CONFIRM_COUNT (3u)
#define PROBE_RECONNECT_CONFIRM_COUNT (2u)
#define BATTERY_LOW_MV_THRESHOLD   (1100u)
#define BATTERY_RECOVER_MV_THRESHOLD (1200u)
#define BATTERY_DEBOUNCE_COUNT     (20u)
/* 测温任务周期参数为 500 tick；120 点窗口约 60 秒，实际随调度和采样耗时变化。 */
#define BATTERY_ADC_AVERAGE_SAMPLES (120u)

#endif
